//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Evaluations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluations()
        {
            this.Results = new HashSet<Results>();
        }
    
        public System.Guid Id { get; set; }
        [Required(ErrorMessage = "the Classroom is required")]
        public System.Guid Classroom_Id { get; set; }
        [Required(ErrorMessage = "the User is required")]
        public System.Guid User_Id { get; set; }
        [Required(ErrorMessage = "the Period is required")]
        public System.Guid Period_Id { get; set; }
        [Required(ErrorMessage = "the Date is required")]
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        [Required(ErrorMessage = "the TotalPoint is required")]
        public int TotalPoint { get; set; }
    
        public virtual Classrooms Classrooms { get; set; }
        public virtual Periods Periods { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }
    }
}
