//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupils
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pupils()
        {
            this.Results = new HashSet<Results>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public short Sex { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public short State { get; set; }
        public System.Guid Tutor_Id { get; set; }
        public System.Guid Classroom_Id { get; set; }
        public System.Guid Level_Id { get; set; }
    
        public virtual Classrooms Classrooms { get; set; }
        public virtual Levels Levels { get; set; }
        public virtual Tutors Tutors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }
    }
}
