//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tutors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tutors()
        {
            this.Pupils = new HashSet<Pupils>();
        }
    
        public System.Guid Id { get; set; }
        [Required(ErrorMessage = "the LastName is required")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "the Firstname is required")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "the Adresse is required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "the Postcode is required")]
        public string PostCode { get; set; }
        [Required(ErrorMessage = "the town is required")]
        public string Town { get; set; }
        [Required(ErrorMessage ="the phone number is required")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^[+33.]?([0-9]{11})$", ErrorMessage = "Not a valid Phone number")]
        public string Tel { get; set; }
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Mail { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pupils> Pupils { get; set; }
    }
}
